### ISSUE TITLE
Feilsituasjon når server returnerer 504

### ISSUE THREAD

**Issue by LtGlahn** [LtGlahn/nvdbapi-V3#6]
Får crash når vi pga 504 - feil prøver å hente data flere ganger (etter 15 sekunders pause). Programmet prøver kun en gang, så crasher det med feilkode

Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/jan/jobb/nvdbapi-V3/nvdbapiV3qgis3.py", line 173, in nvdb2kart
    nvdbsok2qgis( nvdbref, **kwargs )
  File "/home/jan/jobb/nvdbapi-V3/nvdbapiV3qgis3.py", line 314, in nvdbsok2qgis
    mittobj = sokeobjekt.nesteNvdbFagObjekt()
  File "/home/jan/jobb/nvdbapi-V3/nvdbapiv3.py", line 649, in nesteNvdbFagObjekt
    fagdata = self.nesteForekomst()
  File "/home/jan/jobb/nvdbapi-V3/nvdbapiv3.py", line 171, in nesteForekomst
    self.statistikk()
  File "/home/jan/jobb/nvdbapi-V3/nvdbapiv3.py", line 509, in statistikk
    self.antall = stat['antall']
TypeError: 'NoneType' object is not subscriptable

**Comment by LtGlahn** [comment]
Ser ut som om feilen er at vi aldri returnerer noe som helst av data ut igjen til kaller når vi rekursivt prøver på ny...
